version: '3.8'

services:
  odoo:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - /Users/sopiali/Documents/src/nyatech/dev/adems-developers/badingo/react-odoo-app/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-net

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - odoo-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - odoo
      - reactapp
    networks:
      - odoo-net

  reactapp:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - odoo-net

volumes:
  odoo-data:
  db-data:

networks:
  odoo-net:
