version: '3.8'

services:
  react-app:
    build:
      context: ./bunachin
    container_name: react-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - badindo-network

  odoo:
    image: odoo:14
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - HOST=db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - badindo-network

  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - badindo-network

networks:
  badindo-network: